### ISSUE TITLE
[DM003_Get Code] _ Display another message when just only input into [One time token] field and tap on [GET QR CODE] button

### ISSUE THREAD

**Issue by at-cuongnguyen** [queenscity/internship-2019-winter-App01#16]
**Environment:**
- Date : 2020-02-20
- Build version: [DEV] / Version 1.4
- Device: [SM-G965U1] - Samsung s9+ (Android version 10)

**Pre-condition :** 
- [DM003_Get Code] screen is displayed.

**Steps to perform:** 
1. No input in [Identification] textbox.
2. Input 7 digit numbers into [One Time Token] textbox (Ex: 0123456)
3. Tap on [GET QR CODE] button

**Expected result :** 
- **At step 3**: Display error message "Please input on both Identification and One time token fields" below [Identification] textbox 

**Actual result**  
- **At step 3**: Display error message "Please input on both Identification and One time token fields" below [Identification] textbox and another message "Please try again at the bottom of [DM003_Get Code] screen
-----------------------------------
**Image is attached below :** 
![Screenshot_20200220-091815_DemoTrain](https://user-images.githubusercontent.com/59014109/74894646-2f447d80-53c2-11ea-9db6-9bf10672737a.jpg)

**Comment by at-nhungle** [comment]
@at-cuongnguyen 
Issue này và issue https://github.com/queenscity/internship-2019-winter-App01/issues/15 same same rồi em, nên gộp chung 1 issue thôi em.
