### ISSUE TITLE
[DM002_Register] Registered successfully when input space character into [First Name] field

### ISSUE THREAD

**Issue by at-trinhtruong** [queenscity/internship-2019-winter-App01#26]
**Test Environment:**
- Date time: 2020-02-20
- Device: Huawei / Android 8.0.8
- Build: [DEV] Environment / Version 1.4

**Pre-conditions:**
- Open DM002_Register screen

**Steps to Perform:**
1. Input space character into [First Name] field
2. Input correctly into [Last Name] field
3. Select [Birthday]
4. Select [Gender]
5.Select [University]
6. Check [Terms of User] checkbox
7. Tap on [SUBMIT] button

**Actual Result:**
- **At step 7:** Registered successfully
**Expected Result:**
- **At step 2:** Error Message "Please input only alphanumeric into First name" is displayed

**Note:** Also occurs in case [Last Name] file

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/59002360/75124886-b2c4de00-56e4-11ea-97df-469b838201bb.gif)

**Comment by at-nhungle** [comment]
@at-trinhtruong  
Được input bình thường mà em
