### ISSUE TITLE
[DM002_Register] _ Another message is displayed when tap on [Submit] button that has emoji into [First Name] textbox 

### ISSUE THREAD

**Issue by at-cuongnguyen** [queenscity/internship-2019-winter-App01#50]
**Environment:**

- Date : 2020-02-21.
- Build version : [DEV] / Version 1.4.
- Device : [SM-G9565U1] - Samsung s9+ / Android version 10.

**Pre-condition :** 
- [DM002_Register] screen is displayed.

**Steps to perform:**
1. Input emoji (Ex:  🤣 😃 😄 ) into [First Name] textbox.
2. Input/select valid data into remaining fields.
3. Tap on [Submit] button.

**Expected result:** 
- **At step 3** : Display an error message "Please input only alphanumeric into First name"  below the [First name] textbox.

**Actual result :** 
- **At step 3** : 
  - Display an error message "Please input only alphanumeric into First name"  below the [First name] textbox.
  - Display another message "Please fill all required fields" at the bottom of [DM002_Register] screen.
-------------------
**Image is attached below :** 
![Screenshot_20200221-110012_DemoTrain](https://user-images.githubusercontent.com/59014109/75004537-10b3b480-549e-11ea-91e9-6571596cf2b1.jpg)

**Comment by at-nhungle** [comment]
@at-cuongnguyen
Xem comment issue: #54
