### ISSUE TITLE
[DM002_Register] _ Another message is displayed when input into [Last Name] textbox and tap on [Submit] button 

### ISSUE THREAD

**Issue by at-cuongnguyen** [queenscity/internship-2019-winter-App01#52]
**Environment:**

- Date : 2020-02-21.
- Build version : [DEV] / Version 1.4.
- Device : [SM-G9565U1] - Samsung s9+ / Android version 10.

**Pre-condition :** 
- [DM002_Register] screen is displayed.

**Steps to perform:**
1. Input non-alphanumeric characters (Ex: !@#!@%) into [Last Name] textbox.
2. Input/select valid data into remaining fields.
3. Tap on [Submit] button.

**Expected result:** 
- **At step 3** : Display an error message "Please input only alphanumeric into Last name"  below the [Last name] textbox.

**Actual result :** 
- **At step 3** : 
  - Display an error message "Please input only alphanumeric into Last name"  below the [Last name] textbox.
  - Display another message "Please fill all required fields" at the bottom of [DM002_Register] screen.
-------------------
**Image is attached below :** 
![Screenshot_20200221-135019_DemoTrain](https://user-images.githubusercontent.com/59014109/75011082-50d06280-54b1-11ea-8b17-e332530b5a47.jpg)

**Comment by at-nhungle** [comment]
@at-cuongnguyen 
Xem comment issue: https://github.com/queenscity/internship-2019-winter-App01/issues/54
