### ISSUE TITLE
[DM002_Register] _ Another message is displayed when tap on [Submit] button that has character which not latin into [Last Name] textbox

### ISSUE THREAD

**Issue by at-cuongnguyen** [queenscity/internship-2019-winter-App01#53]
**Environment:**

- Date : 2020-02-21.
- Build version : [DEV] / Version 1.4.
- Device : [SM-G9565U1] - Samsung s9+ / Android version 10.

**Pre-condition :** 
- [DM002_Register] screen is displayed.

**Steps to perform:**
1. Input character which not latin (Ex: 大山弓戈) into [Last Name] textbox.
2. Input/select valid data into remaining fields.
3. Tap on [Submit] button.

**Expected result:** 
- **At step 3** : Display an error message "Please input only alphanumeric into Last name"  below the [Last name] textbox.

**Actual result :** 
- **At step 3** : 
  - Display an error message "Please input only alphanumeric into Last name"  below the [Last name] textbox.
  - Display another message "Please fill all required fields" at the bottom of [DM002_Register] screen.
-------------------
**Image is attached below :** 
![Screenshot_20200221-135657_DemoTrain](https://user-images.githubusercontent.com/59014109/75011522-6f832900-54b2-11ea-9a81-c93b5128a353.jpg)

**Comment by at-nhungle** [comment]
@at-cuongnguyen 
Xem comment issue https://github.com/queenscity/internship-2019-winter-App01/issues/54
