### ISSUE TITLE
[DM003_Get Code] QR Code is displayed incorrectly with last digit is 0 when tap on [GET QR CODE]

### ISSUE THREAD

**Issue by at-trinhtruong** [queenscity/internship-2019-winter-App01#73]
**Test Environment:**
- Date time: 2020-02-24
- Device: OPPO F1s / Android 5.1
- Build: [DEV] Environment / Version 1.4

**Pre-conditions:**
- Open DM003_Get Code screen

**Steps to Perform:**
1. Input 8 numbers into [Identification] field
Ex: 51345673
2. Input 8 numbers into [One time token] field
Ex: 14532378
3. Tap on [GET QR CODE] button
4. Check the display of QR Code

**Actual Result:**
- **At step 4:** QR Code is displayed incorrectly

**Expected Result:**
- **At step 4:** QR Code is displayed correctly [Ex: 51345673145323780]

**Note:** Also occurs in case: Last digit is 1, 2, 3, 4, 5, 6, 7, 8, 9

![screenshot_2020-02-24-16-28-39-73](https://user-images.githubusercontent.com/59002360/75434298-e6716380-5983-11ea-9949-83e82fcc3509.png)

**Comment by at-nhungle** [comment]
@at-trinhtruong 
Ở đây trường hợp nào tính cũng sai hay sao em, nói rõ sai ở đâu đi em, phần này có những thành phần nào?
