### ISSUE TITLE
[DM005_Quiz] [GET RESULT] button is enable when tap on [GET RESULT] button.

### ISSUE THREAD

**Issue by at-trinhtruong** [queenscity/internship-2019-winter-App01#80]
**Test Environment:**
- Date time: 2020-02-25
- Device: OPPO F1s / Android 5.1
- Build: [DEV] Environment / Version 1.4

**Pre-conditions:**
- Open DM005_Quiz screen
- All question are selected correctly

**Steps to Perform:**
1. Tap on [GET RESULT] button
2. Check status of [GET RESULT] button

**Actual Result:**
- **At step 2:** [GET RESULT] button is enable.

**Expected Result:**
- **At step 2:** [GET RESULT] button is disable and grey out.

![screenshot_2020-02-25-07-14-25-93](https://user-images.githubusercontent.com/59002360/75207121-72c82e80-57aa-11ea-9b57-b5fc6252896d.png)

**Comment by at-nhungle** [comment]
@at-trinhtruong 
Bug này vs https://github.com/queenscity/internship-2019-winter-App01/issues/94 thì khác nhau gì vậy em???
